name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Check Gradle settings
      run: |
        echo "Checking settings.gradle:"
        if [ -f "settings.gradle" ]; then
          cat settings.gradle
        elif [ -f "settings.gradle.kts" ]; then
          cat settings.gradle.kts
        else
          echo "No settings.gradle file found"
        fi
        
        echo "\nChecking root build.gradle:"
        if [ -f "build.gradle" ]; then
          cat build.gradle
        elif [ -f "build.gradle.kts" ]; then
          cat build.gradle.kts
        else
          echo "No root build.gradle file found"
        fi
        
        echo "\nChecking app/build.gradle:"
        if [ -f "app/build.gradle" ]; then
          cat app/build.gradle
        elif [ -f "app/build.gradle.kts" ]; then
          cat app/build.gradle.kts
        else
          echo "No app/build.gradle file found"
        fi

    - name: List directory structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "\napp directory contents (if exists):"
        ls -la app || echo "app directory not found"
        echo "\nAll build.gradle files:"
        find . -name "build.gradle" -o -name "build.gradle.kts" | grep -v "/build/"

    - name: Try direct build
      run: |
        echo "Trying to build the project directly..."
        gradle assembleRelease

    - name: Find APK files
      run: |
        echo "Searching for APK files..."
        find . -name "*.apk"

    - name: Upload Release APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: |
          **/build/outputs/apk/**/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}