name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: List projects
      run: gradle projects
      
    - name: List tasks
      run: gradle tasks

    - name: List directory structure
      run: |
        echo "Root directory contents:"
        ls -la
        echo "\nAll build.gradle files:"
        find . -name "build.gradle" -o -name "build.gradle.kts" | grep -v "/build/"
        echo "\nDirectory structure:"
        find . -type d -not -path "*/\.*" | sort

    - name: Build APK
      run: |
        # 查找所有的 build.gradle 文件
        BUILD_FILES=$(find . -name "build.gradle" -o -name "build.gradle.kts" | grep -v "/build/")
        
        # 查找包含 android 插件的 build.gradle 文件
        for file in $BUILD_FILES; do
          if grep -q "com.android.application" "$file"; then
            DIR=$(dirname "$file")
            MODULE_NAME=$(basename "$DIR")
            REL_PATH=${DIR#./}
            echo "Found Android application module at: $REL_PATH"
            
            # 如果是根目录
            if [ "$REL_PATH" = "." ]; then
              echo "Building root project"
              gradle assembleRelease
            else
              # 计算模块路径
              MODULE_PATH=${REL_PATH//\//:}
              echo "Building module: $MODULE_PATH"
              gradle :$MODULE_PATH:assembleRelease
            fi
            
            # 退出循环，我们找到了需要构建的模块
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              break
            else
              echo "Build failed for $MODULE_PATH, trying another module if available"
            fi
          fi
        done
        
        # 如果没有找到 Android 应用模块，尝试构建根项目
        if [ -z "$MODULE_NAME" ]; then
          echo "No Android application module found, trying to build root project"
          gradle assembleRelease
        fi

    - name: Find APK files
      run: |
        echo "Searching for APK files..."
        find . -name "*.apk"

    - name: Upload Release APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        files: |
          **/build/outputs/apk/**/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}